### ISSUE TITLE
Don't distribute insecure binary!

### ISSUE THREAD

**Issue by not-so-cool-anymore** [D3VBG/KodFilter#1]
Do not distribute your projects by using precompiled insecure binaries!
Upload the source code and implement proper continuous integration and deployment system that will release stable versions automatically.

**Comment by D3VBG** [comment]
does not show the code so they cannot break it.

**Comment by not-so-cool-anymore** [comment]
Trying to obfuscate or hide source code is useless. It can always be reverse engineered. Distributing binaries only for the purpose of hiding and amateurly protecting insecure source code on GitHub is unprofessional and a clear indicator for the developer's incompetence and lack of proper computer security skills. Furthermore, the tool is aimed for security purposes, but it's not clear if it is safe to be used as such...

**Comment by D3VBG** [comment]
protection no longer works against DDoS, but only for Dos

**Comment by not-so-cool-anymore** [comment]
No matter of that, the above comment is still valid.
