### ISSUE TITLE
Порт

### ISSUE THREAD

**Issue by Stimo1** [D3VBG/KodFilter#2]
Здравствуйте как добавить в неё свой порт для защиты там защяет только стандартные порты

**Comment by D3VBG** [comment]
I am protected ALL ports

**Comment by Stimo1** [comment]
> Я защищен всеми портами

Здравствуй мне нужно с вам поговорить насчёт этой защиту можете написать свои контакты пожалуйста

**Comment by D3VBG** [comment]
https://discord.gg/6evvrsRYYa

**Comment by D3VBG** [comment]
> > Я защищен всеми портами
> 
> Здравствуй мне нужно с вам поговорить насчёт этой защиту можете написать свои контакты пожалуйста

https://discord.gg/6evvrsRYYa

**Comment by Stimo1** [comment]
Я хочу использовать это для игрового сервера мне нужно чтобы он защищал мои порты игровые
